# Generated by Django 5.2.5 on 2025-08-12 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_is_staff_user_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneCIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('integration_type', models.CharField(choices=[('webservice', 'Web Service'), ('file_export', 'File Export/Import'), ('hybrid', 'Hybrid')], max_length=20)),
                ('wsdl_url', models.URLField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('export_path', models.CharField(blank=True, max_length=255)),
                ('import_path', models.CharField(blank=True, max_length=255)),
                ('file_format', models.CharField(choices=[('xml', 'XML'), ('json', 'JSON'), ('csv', 'CSV')], default='xml', max_length=20)),
                ('auto_sync', models.BooleanField(default=False)),
                ('sync_interval', models.PositiveIntegerField(default=60, help_text='Minutes')),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '1C Integration',
                'verbose_name_plural': '1C Integrations',
            },
        ),
        migrations.CreateModel(
            name='BusinessDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('invoice', 'Счёт'), ('act', 'Акт выполненных работ'), ('waybill', 'Накладная'), ('tax_invoice', 'Счёт-фактура'), ('tax_report', 'Налоговая отчётность')], max_length=20)),
                ('document_number', models.CharField(max_length=50, unique=True)),
                ('document_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлен'), ('confirmed', 'Подтверждён'), ('paid', 'Оплачен'), ('cancelled', 'Отменён')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_documents', to='core.company')),
                ('company_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_documents', to='core.company')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orderrequest')),
            ],
            options={
                'ordering': ['-document_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.businessdocument')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('export', 'Export to 1C'), ('import', 'Import from 1C'), ('update', 'Update in 1C')], max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.businessdocument')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.onecintegration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
